/* eslint-disable*/
import { Meteor } from 'meteor/meteor'
import '../imports/api/users'
import { LessonPlans } from '../imports/api/lessonplans'
import { Requests } from '../imports/api/requests'
import { Sims } from '../imports/api/sims'
import { Lessons } from '../imports/api/lessons'
import { Classes } from '../imports/api/classes'
import { Comments } from '../imports/api/comments'
import '../imports/startup/simple-schema-configuration.js'